# Generated by Django 4.0.8 on 2022-12-06 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categorypoll_session_remove_category_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.session'),
        ),
    ]
